name: Docker Image CI

on:
  push:
    branches: [ mkdocs ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag k3d-lab:$(date +%s)
